

# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s 
# and then add one more letter at a random position.
# Find the letter that was added in t.

# Example:
# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.

# class Solution(object):
#     def findTheDifference(self, s, t):
#         """
#         :type s: str
#         :type t: str
#         :rtype: str
#         """

def findTheDifference(s, t):
    """
    :type s: str
    :type t: str
    :rtype: str
    """
    tarStr = list(t)
    for each in s:
    	if each in t:
    		tarStr.remove(each)
    return tarStr[0]

findTheDifference("abcde", "abfcde")
findTheDifference("a", "aa")